server:
  port: 8080

spring:
  datasource:
    name: test
    url: jdbc:mysql://39.108.128.195:3306/arvinzhang
    username: root
    password: arvinzhang
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    host: smtp.qq.com
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    fromMail:
      addr:

## mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yingwu.digital.bean.POJO

logging:
  config: classpath:log4j2.xml




